DROP USER IF EXISTS orderadmin;
DROP USER IF EXISTS orderuser;
CREATE USER orderadmin SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION PASSWORD 'password';
CREATE USER orderuser SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION PASSWORD 'password';